'use strict';

/*
 * build-parts.js — compile the face-components/ SVG pack into a single
 * parts-data.js that the app loads at runtime (offline-friendly, no per-part
 * fetches). Run from the repo root:  node tools/build-parts.js
 *
 * Source: face-components/ (heuristic decomposition of the OpenMoji face set).
 * Art licence: OpenMoji — CC BY-SA 4.0 (https://openmoji.org).
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const PACK = path.join(ROOT, 'face-components');
const MANIFEST = path.join(PACK, 'components.json');
const OUT = path.join(ROOT, 'parts-data.js');

// pack type  ->  app layer  (null = handled separately / dropped)
const TYPE_TO_LAYER = {
  face: 'face',
  eyes: 'eyes',
  brows: 'eyebrows',
  nose: 'nose',
  mouth: 'mouth',
  extras: 'extras',
  ears: 'extras',   // fold the lone ears part into extras
  arms: 'arms',     // pulled out for the dance system, not a pickable layer
};

// layers that should offer a "None" (blank) option at the front
const OPTIONAL = new Set(['eyebrows', 'nose', 'extras']);

// Extract the inner markup of an OpenMoji part SVG and tidy it for inlining:
// drop the <svg> wrapper and the <?xml?>/comments, strip id="" attributes
// (avoids duplicate-id soup once hundreds are in the DOM), collapse whitespace.
function innerSvg(raw) {
  let s = raw;
  s = s.replace(/<\?xml[\s\S]*?\?>/g, '');
  s = s.replace(/<!--[\s\S]*?-->/g, '');
  s = s.replace(/<svg\b[^>]*>/i, '');
  s = s.replace(/<\/svg>/i, '');
  s = s.replace(/\sid="[^"]*"/g, '');
  s = s.replace(/\s+/g, ' ').trim();
  return s;
}

const manifest = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));

const layers = { face: [], eyes: [], eyebrows: [], nose: [], mouth: [], extras: [] };
const arms = [];
let skipped = 0;

for (const c of manifest.components) {
  const layer = TYPE_TO_LAYER[c.type];
  if (!layer) { skipped++; continue; }

  const svg = innerSvg(fs.readFileSync(path.join(PACK, c.file), 'utf8'));
  if (!svg) { skipped++; continue; }            // empty after tidy — skip

  const entry = { name: c.source_emoji, svg };
  if (layer === 'arms') arms.push(entry);
  else layers[layer].push(entry);
}

// prepend the blank option where a layer is optional
for (const l of Object.keys(layers)) {
  if (OPTIONAL.has(l)) layers[l].unshift({ name: 'None', svg: '' });
}

const banner =
`'use strict';
/* AUTO-GENERATED by tools/build-parts.js — do not edit by hand.
 * Emoji art: OpenMoji (https://openmoji.org), licensed CC BY-SA 4.0.
 * ${manifest.component_count} components from ${manifest.emoji_count} faces, viewBox 0 0 72 72.
 */
`;

const body =
`const PARTS = ${JSON.stringify(layers, null, 0)};
const PACK_ARMS = ${JSON.stringify(arms, null, 0)};
`;

fs.writeFileSync(OUT, banner + body + '\n');

const counts = Object.entries(layers).map(([k, v]) => `${k}:${v.length}`).join('  ');
console.log(`Wrote ${path.relative(ROOT, OUT)}`);
console.log(`  ${counts}  arms:${arms.length}  (skipped ${skipped})`);
console.log(`  ${(fs.statSync(OUT).size / 1024).toFixed(0)} KB`);
